version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: onboarding-postgres54
    ports:
      - "5494:5432"
    environment:
      POSTGRES_DB: employee_onboarding
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: onboarding-backend54
    ports:
      - "3094:3094"
    environment:
      PORT: 3094
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: employee_onboarding
      DB_PASSWORD: admin123
      DB_PORT: 5432
    volumes:
      - ./Backend/Uploads:/app/Uploads
    depends_on:
      - postgres

  employee-onboarding:
    build: ./Employee-Onboarding
    container_name: employee-onboarding54
    ports:
      - "8189:80"
    depends_on:
      - backend

  hr-onboarding:
    build: ./HR-Onboarding
    container_name: hr-onboarding54
    ports:
      - "8190:80"
    depends_on:
      - backend

volumes:
  db_data:

